#To compose this docker-compose.yaml file use 'docker-compose -f <file_name> up'
#Add the '-d' flag at the end for detatched execution
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - 4444:4444
    volumes:
      - .:/etc/selenoid/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/selenoid/video/:/opt/selenoid/video
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/selenoid/video    
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - 8090:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_106.0:
    image: selenoid/vnc_chrome:106.0
    network_mode: bridge
    container_name: chrome_106.0
    shm_size: 2g
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
  firefox_106.0:
    image: selenoid/vnc_firefox:106.0
    network_mode: bridge
    container_name: firefox_106.0
    shm_size: 256m
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    volumes:
      - /dev/shm:/dev/shm
  video_recorder:
    image: selenoid/video-recorder:latest-release
    network_mode: bridge
    container_name: video-recorder
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    volumes:
      - /dev/shm:/dev/shm
    